### ISSUE TITLE
Typewriter effect incomplete

### ISSUE THREAD

**Issue by WilliamFerns1** [Automa-Automations/web-app#2]
## Problem:
1. The typewriter effect is not completed. 
2. The code quality can be better. Remove unnecessary console.logs, clean up the code, and add in meaningful comments. 

## Tasks:
Submit a PR that closes this issue, solving the problems mentioned above by doing these tasks:
- [x] Make so that the typewriter effect removes the text as expected, simulating "ctr+backspace". 
- [x] Change up the order of the typewriter function parameters to make more sense.
- [x] Remove unnecessary console.logs.
- [x] Add in meaningful comments. Check through those comments, fix spelling mistakes, make it better.
- [x] Turn the typewriter effect into multiple subfunctions. For example `addText`, `removeText`, ect...
- [x] Record a high quality tutorial based video, where you go through the HTML, CSS, and JS to explain the code. Upload that video on Youtube with a title along the lines of **How to make typewriter effect HTML, CSS, JS**.
- [ ] Make a PR that resolves this issue. Follow the PR template, and make a Trello task for Simon to review the PR.
